# Preconfigured SALT VM with a salt-master & salt-minion couple
# you ll need at boot to accept the minion key with salt-key -A
FROM makinacorpus/ubuntu
MAINTAINER Mathieu Le Marec Pasquet <kiorky@cryptelium.net>
ADD docker-postinst.sh /etc/docker-postinst.sh
CMD ["/sbin/init"]
