# Preconfigured SALT VM with a salt-master & salt-minion couple
# you ll need at boot to accept the minion key with salt-key -A
FROM makinacorpus/ubuntu
ADD postinst.sh /etc/docker-postinst.sh
CMD ["/sbin/init"]
