#!/bin/sh

set -e

if dpkg-maintscript-helper supports rm_conffile; then
	dpkg-maintscript-helper rm_conffile \
		/etc/logcheck/ignore.d.server/ntp 1:4.2.6+dfsg-1 -- "$@"
	dpkg-maintscript-helper rm_conffile \
		/etc/dhcp3/dhclient-enter-hooks.d/ntp 1:4.2.6+dfsg-1 -- "$@"
	dpkg-maintscript-helper rm_conffile \
		/etc/network/if-up.d/ntp 1:4.2.6+dfsg-1 -- "$@"
fi

if dpkg-maintscript-helper supports mv_conffile; then
	dpkg-maintscript-helper mv_conffile \
		/etc/dhcp3/dhclient-exit-hooks.d/ntp \
		/etc/dhcp/dhclient-exit-hooks.d/ntp \
		1:4.2.6.p1+dfsg-1 -- "$@"
fi

if [ "$1" = "configure" ]; then
	adduser --system --quiet --group --no-create-home ntp || :
	chown -R ntp:ntp /var/lib/ntp /var/log/ntpstats
fi

installinit_error() {
	exit $?
}

# # Automatically added by dh_apparmor
# if [ "$1" = "configure" ]; then
#     APP_PROFILE=/etc/apparmor.d/usr.sbin.ntpd
#     if [ -f "$APP_PROFILE" ]; then
#         # Add the local/ include
#         LOCAL_APP_PROFILE=/etc/apparmor.d/local/usr.sbin.ntpd
#
#         test -e "$LOCAL_APP_PROFILE" || {
#             tmp=`mktemp`
#         cat <<EOM > "$tmp"
# # Site-specific additions and overrides for usr.sbin.ntpd.
# # For more details, please see /etc/apparmor.d/local/README.
# EOM
#             mkdir `dirname $LOCAL_APP_PROFILE` 2>/dev/null || true
#             mv -f "$tmp" "$LOCAL_APP_PROFILE"
#             chmod 644 "$LOCAL_APP_PROFILE"
#         }
#
#         # Reload the profile, including any abstraction updates
#         if aa-status --enabled 2>/dev/null; then
#             apparmor_parser -r -T -W "$APP_PROFILE" || true
#         fi
#     fi
# fi
# End automatically added section
# Automatically added by dh_installinit
if [ -x "/etc/init.d/ntp" ]; then
	if [ ! -e "/etc/init/ntp.conf" ]; then
		update-rc.d ntp start 23 2 3 4 5 . stop 77 1 . >/dev/null
	fi
	invoke-rc.d ntp start || installinit_error
fi
# End automatically added section

